# # #   Copyright PDGH Minecraft Servers & HostLoad © 2013-XXXX   # # #
# # #                Todos os direitos reservados!                # # #
# # #   Uso apenas para a PDGH.com.br e https://HostLoad.com.br   # # #
# # # Caso você tenha acesso a esse sistema,você é privilegiado! # # #
grupos:
  1:
    armas:
    - 258
    - 286
    erro: '&cÉ possível atirar apenas com a primeira &aSniper&c que já está em sua hotbar.'
  2:
    armas:
    - 2256
    - 2264
    - 290
    - 291
    - 292
    - 294
    - 352
    erro: '&cÉ possível atirar apenas com o o primeiro &aRifle/Sub&c que já está em sua hotbar.'
  3:
    armas:
    - 2259
    - 359
    erro: '&cÉ possível atirar apenas com o a primeira &aPistola&c que já está em sua hotbar.'
  4:
    armas:
    - 285
    - 257
    - 279
    - 284
    - 256
    erro: '&cÉ possível atirar apenas com o a primeira &aShotgun/RPG&c que já está em sua hotbar.'